## Gaussian Elimination

In [26]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [27]:
# Example Usage
A = [[2, 3, -1], [4, -2, 2], [-2, 1, 2]]
b = [5, 6, -1]
solution = gaussian_elimination(A, b)
print(A, b)
print(f"Solution: {solution}")

[[4, -2, 2], [0.0, 4.0, -2.0], [0.0, 0.0, 3.0]] [6, 2.0, 2.0]
Solution: [1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [28]:
answer = np.linalg.solve(A,b)
print(answer)

[1.58333333 0.83333333 0.66666667]


# LU Decomposition

In [2]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    # modifying the original matrix
    # modifying the original matrix
    
    for i in range(n):
        if U[i, i] == 0:
            raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.") 
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]  # Multiplier for row
            L[j, i] = factor  # Store multiplier in L
            
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

In [3]:
# Example usage
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [7]:
print(np.matmul(L,U))# OR print(L@U)

[[ 4.  7. -1.]
 [-2.  1.  2.]
 [ 2.  3.  1.]]


In [5]:
import numpy as np
from scipy.linalg import lu

# Example matrix
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])
# Perform LU Decomposition
P, L, U = lu(A)

print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]
