In [1]:
import numpy as np

#creating a vector
v1 = np.array([1, 2, 3]) #A 3-Dimensional Vector
v2 = np.array([4,5,6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [5]:
#Vector operations: basic
v_add = v1 + v2
v_subtract = v1 - v2

print(v_add)
print(v_subtract)

[5 7 9]
[-3 -3 -3]


In [7]:
#Scalar multiplication
scalar = 2
v_scaled = scalar * v1

print(v_scaled)

[2 4 6]


In [9]:
#Dot product
dot_product = np.dot(v1, v2) # v1 dot v2 = (1*4) + (2*5) + (3*6)

print(dot_product)

32


In [12]:
#Magnitude (Norm) of Vector
magnitude = np.linalg.norm(v1)

print(magnitude)

3.7416573867739413


# Matrices and Matrix Operations

In [13]:
#Creating a 2x3 matrix
A = np.array([[1,2,3], [4,5,6]])

print(A)

[[1 2 3]
 [4 5 6]]


In [14]:
#Creating a 3x3 matrix
B = np.array([[7,8,9],[10,11,12],[13,14,15]])

print(B)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [23]:
#Matrix addition and subtraction
C = np.array([[1,2,3],[4,5,6]])

mat_add = A + C
mat_sub = A - C

print("A + C:\n", mat_add)
print("A - C:\n", mat_sub)

A + C:
 [[ 2  4  6]
 [ 8 10 12]]
A - C:
 [[0 0 0]
 [0 0 0]]


In [27]:
##Matrix multiplication
#Multiplying A (2x3) and B (3x3)
mat_mul = np.dot(A,B) #or A @ B

print("A * B:\n", mat_mul)

A * B:
 [[ 66  72  78]
 [156 171 186]]


In [28]:
#The transpose of a matrix swaps its rows with its columns.
transpose_A = A.T

print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


# Python code to solve the system

In [33]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
print(A)
print(b)

# Solve the system A * x = b
x = np.linalg.solve(A, b)

print("\nSolution (x, y):", x)

[[ 2  3]
 [ 4 -1]]
[5 3]

Solution (x, y): [1. 1.]


# Finding Eigenvalues and Eigenvectors in Python:

In [36]:
# Define matrix A
A = np.array([[2, 1], [1, 2]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues: [3. 1.]

Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [42]:

A = np.array([[4,7],[2,6]])
A_inverse = np.linalg.inv(A)

print(A)
print("\n", A_inverse)

[[4 7]
 [2 6]]

 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [44]:
#Check
identity = np.dot(A, A_inverse)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


# SVD (Singular Value Decomposition) in Python

In [49]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("\nSigma values:\n", sigma)
print("\nV^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Sigma values:
 [9.52551809 0.51430058]

V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
